# Generated by Django 4.1.5 on 2023-01-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounties', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bounty',
            old_name='id_creator',
            new_name='creator',
        ),
        migrations.AddField(
            model_name='bounty',
            name='target_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bounty',
            name='target_description',
            field=models.TextField(blank=True, default='Jest słaby i wiele zapomniał', null=True),
        ),
        migrations.AddField(
            model_name='bounty',
            name='target_difficulty',
            field=models.IntegerField(choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], default=1),
        ),
        migrations.AddField(
            model_name='bounty',
            name='target_name',
            field=models.CharField(default='Bezimienny', max_length=100),
        ),
        migrations.AddField(
            model_name='bounty',
            name='target_reward',
            field=models.IntegerField(default=100),
        ),
    ]
