# Generated by Django 4.1.5 on 2023-01-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounties', '0003_alter_bounty_creator_alter_bounty_target_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='hunter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='target_completed',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='target_completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='target_description',
            field=models.TextField(blank=True, default='Jest słaby i wiele zapomniał', max_length=375),
        ),
    ]
