# Generated by Django 4.1.5 on 2023-01-18 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bounties', '0004_bounty_hunter_alter_bounty_target_completed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bounty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bounties.bounty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
                'default_related_name': 'observes',
            },
        ),
    ]
