# Generated by Django 4.1.5 on 2023-01-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounties', '0005_observe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observe',
            options={'default_related_name': 'observes', 'ordering': ['user_id']},
        ),
        migrations.RemoveField(
            model_name='observe',
            name='bounty',
        ),
        migrations.RemoveField(
            model_name='observe',
            name='user',
        ),
        migrations.AddField(
            model_name='observe',
            name='bounty_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='observe',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
