# Generated by Django 4.1.5 on 2023-01-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounties', '0006_alter_observe_options_remove_observe_bounty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='observed',
            field=models.BooleanField(default=False),
        ),
    ]
