# Generated by Django 4.1.5 on 2023-01-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounties', '0007_bounty_observed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='target_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='target_completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='target_posted_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
