# Generated by Django 4.1.5 on 2023-01-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounties', '0009_alter_bounty_target_completed_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='target_completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='target_posted_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
